/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIdRouteImport } from './routes/member.$id'
import { Route as DistrictSlugRouteImport } from './routes/district.$slug'
import { Route as LegislationSessionTypeNumberRouteImport } from './routes/legislation.$session.$type.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIdRoute = MemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictSlugRoute = DistrictSlugRouteImport.update({
  id: '/district/$slug',
  path: '/district/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislationSessionTypeNumberRoute =
  LegislationSessionTypeNumberRouteImport.update({
    id: '/legislation/$session/$type/$number',
    path: '/legislation/$session/$type/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/district/$slug': typeof DistrictSlugRoute
  '/member/$id': typeof MemberIdRoute
  '/legislation/$session/$type/$number': typeof LegislationSessionTypeNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/district/$slug': typeof DistrictSlugRoute
  '/member/$id': typeof MemberIdRoute
  '/legislation/$session/$type/$number': typeof LegislationSessionTypeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/district/$slug': typeof DistrictSlugRoute
  '/member/$id': typeof MemberIdRoute
  '/legislation/$session/$type/$number': typeof LegislationSessionTypeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/district/$slug'
    | '/member/$id'
    | '/legislation/$session/$type/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/district/$slug'
    | '/member/$id'
    | '/legislation/$session/$type/$number'
  id:
    | '__root__'
    | '/'
    | '/district/$slug'
    | '/member/$id'
    | '/legislation/$session/$type/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictSlugRoute: typeof DistrictSlugRoute
  MemberIdRoute: typeof MemberIdRoute
  LegislationSessionTypeNumberRoute: typeof LegislationSessionTypeNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/$id': {
      id: '/member/$id'
      path: '/member/$id'
      fullPath: '/member/$id'
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/$slug': {
      id: '/district/$slug'
      path: '/district/$slug'
      fullPath: '/district/$slug'
      preLoaderRoute: typeof DistrictSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislation/$session/$type/$number': {
      id: '/legislation/$session/$type/$number'
      path: '/legislation/$session/$type/$number'
      fullPath: '/legislation/$session/$type/$number'
      preLoaderRoute: typeof LegislationSessionTypeNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictSlugRoute: DistrictSlugRoute,
  MemberIdRoute: MemberIdRoute,
  LegislationSessionTypeNumberRoute: LegislationSessionTypeNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
