/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as VoteIdRouteImport } from './routes/vote.$id'
import { Route as SessionsSessionRouteImport } from './routes/sessions.$session'
import { Route as MemberIdRouteImport } from './routes/member.$id'
import { Route as DistrictSlugRouteImport } from './routes/district.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteIdRoute = VoteIdRouteImport.update({
  id: '/vote/$id',
  path: '/vote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionRoute = SessionsSessionRouteImport.update({
  id: '/sessions/$session',
  path: '/sessions/$session',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIdRoute = MemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictSlugRoute = DistrictSlugRouteImport.update({
  id: '/district/$slug',
  path: '/district/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/district/$slug': typeof DistrictSlugRoute
  '/member/$id': typeof MemberIdRoute
  '/sessions/$session': typeof SessionsSessionRoute
  '/vote/$id': typeof VoteIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/district/$slug': typeof DistrictSlugRoute
  '/member/$id': typeof MemberIdRoute
  '/sessions/$session': typeof SessionsSessionRoute
  '/vote/$id': typeof VoteIdRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/district/$slug': typeof DistrictSlugRoute
  '/member/$id': typeof MemberIdRoute
  '/sessions/$session': typeof SessionsSessionRoute
  '/vote/$id': typeof VoteIdRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/district/$slug'
    | '/member/$id'
    | '/sessions/$session'
    | '/vote/$id'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/district/$slug'
    | '/member/$id'
    | '/sessions/$session'
    | '/vote/$id'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/district/$slug'
    | '/member/$id'
    | '/sessions/$session'
    | '/vote/$id'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DistrictSlugRoute: typeof DistrictSlugRoute
  MemberIdRoute: typeof MemberIdRoute
  SessionsSessionRoute: typeof SessionsSessionRoute
  VoteIdRoute: typeof VoteIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote/$id': {
      id: '/vote/$id'
      path: '/vote/$id'
      fullPath: '/vote/$id'
      preLoaderRoute: typeof VoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$session': {
      id: '/sessions/$session'
      path: '/sessions/$session'
      fullPath: '/sessions/$session'
      preLoaderRoute: typeof SessionsSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/$id': {
      id: '/member/$id'
      path: '/member/$id'
      fullPath: '/member/$id'
      preLoaderRoute: typeof MemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/district/$slug': {
      id: '/district/$slug'
      path: '/district/$slug'
      fullPath: '/district/$slug'
      preLoaderRoute: typeof DistrictSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DistrictSlugRoute: DistrictSlugRoute,
  MemberIdRoute: MemberIdRoute,
  SessionsSessionRoute: SessionsSessionRoute,
  VoteIdRoute: VoteIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
